cc_binary(
    name = "ArcadeApp",
    srcs = [ 
        "ArcadeApp.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "PracticeProblems",
    srcs = [ 
        "PracticeProblems.cpp",
    ],
    visibility = ["//visibility:public"],
)