cc_binary(
    name = "ArcadeApp",
    srcs = [ 
        "ArcadeApp.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "Fraction",
    srcs = [ 
        "Fraction.cpp",
    ],
    visibility = ["//visibility:public"],
)